
include:
  - project: global-templates/devex
    file: '.template.yml'
    ref: main
  - project: cloudguard-integrations/ci-utils
    ref: master
    file: ci/.gitlab-ci-analysis.yml
  - project: cloudguard-integrations/ci-utils
    ref: master
    file: ci/.gitlab-ci-verify-jira.yml
  - project: cloudguard-integrations/ci-utils
    ref: master
    file: ci/.gitlab-ci-github-mirroring.yml


workflow:
  rules:
    - when: always


stages:
  - analysis
  - test_native_templates
  - Verify
  - upload
  - github_mirroring


##### Analysis Jobs #####
shellcheck:
  stage: analysis
  script:
    - IGNORE_FILES=$(cat .shellcheckignore)
    - echo "---Ignoring files from shellcheckignore---"
    - echo "$IGNORE_FILES"
    - find . -name "*.sh" | grep -v "$IGNORE_FILES" | xargs shellcheck -e SC1071


pycodestyle:
  allow_failure: true


#### Tests for native cloud templates ####

#### Azure ARM Templates ####
test_azure_arm:
  stage: test_native_templates
  variables:
    solutions: gateway-load-balancer ha management mds single vmss vwan
  image: mcr.microsoft.com/azure-powershell:latest
  parallel:
    matrix: 
      - SOLUTION: [gateway-load-balancer, ha, management, mds, single, vmss, vwan]
  script:
    - apt update
    - apt install git -y
    - git clone https://github.com/Azure/arm-ttk.git
    - |
      echo "Testing marketplace-$SOLUTION"
      pwsh -c '
        Import-Module ./arm-ttk/arm-ttk/arm-ttk.psd1;
        Test-AzTemplate -TemplatePath  ./azure/templates/'marketplace-$SOLUTION'/ -Skip "apiVersions Should Be Recent" | Tee-Object -Variable TestResults;
        $TestFailures =  $TestResults | Where-Object { -not $_.Passed } ;
        If ($TestFailures -ne $null) {
          echo $TestFailures;
          exit 1;
        }
      '


test_azure_china_arm:
  stage: test_native_templates
  variables:
    solutions: gateway-load-balancer ha management mds single vmss vwan
  image: mcr.microsoft.com/azure-powershell:latest
  parallel:
    matrix: 
      - SOLUTION: [gateway-load-balancer, ha, management, mds, single, vmss, vwan]
  script:
    - apt update
    - apt install git -y
    - git clone https://github.com/Azure/arm-ttk.git
    - |
      echo "Testing marketplace-$SOLUTION"
      pwsh -c '
        Import-Module ./arm-ttk/arm-ttk/arm-ttk.psd1;
        Test-AzTemplate -TemplatePath  ./china/azure/'marketplace-$SOLUTION'/ -Skip "apiVersions Should Be Recent" | Tee-Object -Variable TestResults;
        $TestFailures =  $TestResults | Where-Object { -not $_.Passed } ;
        If ($TestFailures -ne $null) {
          echo $TestFailures;
          exit 1;
        }
      '
  allow_failure: true


upload_azure_templates_to_s3:
  stage: upload
  image: artifactory-product.checkpoint.com/docker-local/cloudguard-integrations/${CGNS_RUNNER_IMAGE}
  only:
    - master
    - staging
  script:
    - apt-get install -y jq
    - git clone -b "master" https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.locsec.net/cloudguard-integrations/ci-utils.git ${PROJECT_PATH}
    - source ci-utils/utils/aws_credentials/generate_aws_credentials.sh
    - bucket="azure.templates"
    - lambda="azure.templates-lambda"
    - if [[ ${CI_COMMIT_REF_NAME} == "master" ]]; then
    -     bucket="${bucket}.prod"
    -     lambda="${lambda}.prod"
    - fi
    - chmod +x .internal/azure_scripts/*
    - python3 .internal/azure_scripts/build_all.py -b qa
    - python3 .internal/azure_scripts/upload_templates.py --bucket ${bucket} --lambda-bucket ${lambda} --templates all
